name: nmma

channels:
- conda-forge

dependencies:
- python=3.9.*
- pip
- pip:
  - arrow==1.2.2
  - astropy==5.1
  - certifi==2022.6.15
  - charset-normalizer==2.1.0
  - cycler==0.11.0
  - fonttools==4.36.0
  - healpy==1.16.1
  - idna==3.3
  - kiwisolver==1.4.4
  - matplotlib==3.5.3
  - numpy==1.23.2
  - packaging==21.3
  - Pillow==9.2.0
  - pyerfa==2.0.0.1
  - pyparsing==3.0.9
  - python-dateutil==2.8.2
  - PyYAML==6.0
  - requests==2.28.1
  - scipy==1.9.0
  - six==1.16.0
  - urllib3==1.26.11
